[default.extend-words]
# IST: acronym for Interrupt Stack Table.
ist = "ist"
ists = "ists"
# DNE: acronym for Does Not Exist.
dne = "dne"
# ba: acronym for BinAllocator.
ba = "ba"
# PnCH: Privilege level n's Configuration register for Hypervisor.
pn = "pn"
pnch = "pnch"
