name: Runtime Tests (no kvm)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  ZIG_VERSION: 0.15.1

jobs:
  runtime_test:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/hugin:latest
    strategy:
      fail-fast: false
      matrix:
        BUILD_TYPE: [Debug, ReleaseSafe, ReleaseFast]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependency
        run: |
          apt update
          apt install -y \
            curl \
            wget \
            tar \
            xz-utils \
            mtools \
            device-tree-compiler \
            wget \
            cpio \
            unzip \
            rsync \
            sudo \
            fdisk \
            dosfstools \
            file \
            socat \
            qemu-system-arm

      - name: Install zig
        run: |
          curl https://ziglang.org/download/${{env.ZIG_VERSION}}/zig-x86_64-linux-${{env.ZIG_VERSION}}.tar.xz -L -o zig.tar.xz
          tar -xf zig.tar.xz
          echo "$(pwd)/zig-x86_64-linux-${{env.ZIG_VERSION}}" >> $GITHUB_PATH

      - name: Runtime Tests (test init)
        run: |
          zig build install \
            -Dlog_level=debug \
            -Doptimize=${{ matrix.BUILD_TYPE }} \
            -Druntime_test \
            -Duboot=$UBOOT \
            -Dguest=/opt/Image \
            -Dguestdisk=/opt/DISK0
          bash ./scripts/runtime_test.bash \
            --uboot $UBOOT \
            --expect-timeout
